### ISSUE TITLE
Possibility to transform values before being saved to the index

### ISSUE THREAD

**Issue by nckrtl** [kind-work/meili-search#4]
Hi, I was wondering if it's possible to do some operations on the fields that are being set in meili-search.php before they are being submitted to the index.

For example I'd like to add the reading time of articles, which is based on the length of the content. In antlers I can do it like this on the fly: `{{ bard_content | flatten | join | strip_tags | read_time }}`

Or is is only possible to just store the value of available keys. Currently as a work-around I'm using the AfterEntrySafe listener and calculate + store the reading time under a separate key "reading_time" in the entry (which I added to the blueprint).

Another small note: I noticed the documentation is no longer compatible with the latest version of MeiliSearch (v0.18.1). MeiliSearch should now be instantiated like:

```
import { MeiliSearch } from "meilisearch";

window.client = new MeiliSearch({
    host: "https://search.nckrtl.com",
    apiKey: "master-key", 
});
```

instead of 
```
import MeiliSearch from "meilisearch";

window.client = new MeiliSearch({
    host: "https://search.nckrtl.com",
    apiKey: "public-key", 
});
```

Also the `getIndex` method been changed to `index`. So this:

```
    index: window.client.getIndex('Your Index UID Goes Here'),
    async search() {
      this.state = 'searching';
      this.results = await this.index.search(this.searchString);
    }
```

Should be:
```
    index: window.client.index('Your Index UID Goes Here'),
    async search() {
      this.state = 'searching';
      this.results = await this.index.search(this.searchString);
    }
```

source: https://github.com/meilisearch/meilisearch-js

**Comment by jcohlmeyer** [comment]
Thanks for pointing out the changes in the MeiliSearch JS API. I have made those changes to the Readme.

I will look into the possibility of using antlers code to transform values before saving them to the index.

**Comment by nckrtl** [comment]
Thanks!

**Comment by jcohlmeyer** [comment]
This has been added in `v1.1.0` @nckrtl

**Comment by nckrtl** [comment]
Looks awesome, will try it out tomorrow

**Comment by jcohlmeyer** [comment]
Hey, just following up to see if it all worked as you expected @nckrtl ?

**Comment by nckrtl** [comment]
Hey Johnathan, unfortunately I wasn't able to check it out today. Tomorrow is also busy but I'll do my best to try it out first thing in the morning.

**Comment by jcohlmeyer** [comment]
No rush at all, just wondering. Do let me know when you do get a chance to check it out. Thanks :)

**Comment by nckrtl** [comment]
It works beautifully!
