### ISSUE TITLE
Multisite languages

### ISSUE THREAD

**Issue by tao** [kind-work/meili-search#5]
I'm having trouble figuring out how to add the site locale to the search index. Is that supported by the addon?

```
'indexes' => [
    'speeches' => [
        'collection:speeches' => [
                'title', 
                'locale', 
                'site', 
                'site-handle' => '{{ site:handle }}', 
                'site-locale' => '{{ site:locale }}'
            ],
        ],
    ]
```

**Comment by jcohlmeyer** [comment]
Ideally that should work on the latest version. If it does not it is a bug. I will look into this but I may not be able to get around to it for a few weeks.

**Comment by tao** [comment]
Okay no rush, it seems like MeiliSearch won't be a good fit for this project because of the word limit but it may be useful to confirm this is working when you get a chance.

**Comment by jcohlmeyer** [comment]
Sorry, I have come to the conclusion that I am unable to support this addon, it should continue to work, but if you need support, I suggest checking out: https://statamic.com/addons/elvenstar/statamic-meilisearch
