### ISSUE TITLE
Version confict meilisearch/meilisearch-php

### ISSUE THREAD

**Issue by rmenner** [kind-work/meili-search#6]
Ended Up bumping meilisearch/meilisearch-php to 0.18 in a fork so that I could use it alongside a laravel integration that required that version. No issues that I have found. I suggest maybe using this format ">=0.15" to allow anything above or equal to that version.

**Comment by abuhurairah-aar** [comment]
Same here, I'm also facing that issue

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires kind-work/meili-search ^1.1 -> satisfiable by kind-work/meili-search[v1.1.0].
    - kind-work/meili-search v1.1.0 requires meilisearch/meilisearch-php ^0.15 -> found meilisearch/meilisearch-php[v0.15.0, v0.15.1] but it conflicts with your root composer.json require (^0.21.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require kind-work/meili-search:*" to figure out if any version is installable, or "composer require kind-work/meili-search:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by jcohlmeyer** [comment]
Sorry, I have come to the conclusion that I am unable to support this addon, it should continue to work, but if you need support, I suggest checking out: https://statamic.com/addons/elvenstar/statamic-meilisearch
